/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package JavaDB;
import static JavaDB.DB.getConection;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.*;

/**
 *
 * @author java
 */
public class CRUD extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement ps = null;
    DefaultTableModel modelo;
    Statement st;
    ResultSet rs;
    int id;
    
    private void limpiarCajas() {
        cname.setText(null);
        csurname.setText(null);
        cnameact.setText(null);
        csurnameact.setText(null);
        cidact.setText(null);
        ciddel.setText(null);
    }
   

    /**
     * Creates new form CRUD
     */
    public CRUD() {
        initComponents();
        this.modelo = (DefaultTableModel) TablaDatos.getModel();
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        botonCrear = new javax.swing.JButton();
        botonActualizar = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        panelActualizar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cnameact = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        csurnameact = new javax.swing.JTextField();
        botonGuardarActualizar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        botonVolverActualizar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cidact = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        panelCrear = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cname = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        csurname = new javax.swing.JTextField();
        botonGuardarCrear = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        botonVolverCrear = new javax.swing.JButton();
        panelBorrar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        botonBorrarBorrar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        botonVolverBorrar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        ciddel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD MySQL");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setPreferredSize(new java.awt.Dimension(960, 540));
        getContentPane().setLayout(null);

        jLabel1.setText("¿Qué quieres hacer?");
        Menu.add(jLabel1);

        botonCrear.setText("Crear");
        botonCrear.setMaximumSize(new java.awt.Dimension(83, 22));
        botonCrear.setMinimumSize(new java.awt.Dimension(83, 22));
        botonCrear.setPreferredSize(new java.awt.Dimension(83, 22));
        botonCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCrearActionPerformed(evt);
            }
        });
        Menu.add(botonCrear);

        botonActualizar.setText("Actualizar");
        botonActualizar.setMaximumSize(new java.awt.Dimension(83, 22));
        botonActualizar.setMinimumSize(new java.awt.Dimension(83, 22));
        botonActualizar.setPreferredSize(new java.awt.Dimension(83, 22));
        botonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActualizarActionPerformed(evt);
            }
        });
        Menu.add(botonActualizar);

        botonBorrar.setText("Borrar");
        botonBorrar.setMaximumSize(new java.awt.Dimension(83, 22));
        botonBorrar.setMinimumSize(new java.awt.Dimension(83, 22));
        botonBorrar.setPreferredSize(new java.awt.Dimension(83, 22));
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        Menu.add(botonBorrar);

        getContentPane().add(Menu);
        Menu.setBounds(6, 6, 122, 120);

        panelActualizar.setVisible(false);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre:");

        cnameact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameactActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Apellido:");

        csurnameact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csurnameactActionPerformed(evt);
            }
        });

        botonGuardarActualizar.setText("Guardar");
        botonGuardarActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActualizarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Actualizar Actor");

        botonVolverActualizar.setText("Cancelar");
        botonVolverActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActualizarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("ID:");

        cidact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelActualizarLayout = new javax.swing.GroupLayout(panelActualizar);
        panelActualizar.setLayout(panelActualizarLayout);
        panelActualizarLayout.setHorizontalGroup(
            panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, panelActualizarLayout.createSequentialGroup()
                        .addComponent(botonGuardarActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVolverActualizar))
                    .addGroup(panelActualizarLayout.createSequentialGroup()
                        .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(csurnameact, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cnameact, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cidact, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, panelActualizarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel4)
                        .addGap(44, 44, 44)))
                .addContainerGap())
        );

        panelActualizarLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel9});

        panelActualizarLayout.setVerticalGroup(
            panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelActualizarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cidact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cnameact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(csurnameact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(panelActualizarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarActualizar)
                    .addComponent(botonVolverActualizar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelActualizar);
        panelActualizar.setBounds(6, 6, 233, 200);

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TablaDatos);
        if (TablaDatos.getColumnModel().getColumnCount() > 0) {
            TablaDatos.getColumnModel().getColumn(0).setMinWidth(50);
            TablaDatos.getColumnModel().getColumn(0).setPreferredWidth(50);
            TablaDatos.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(260, 0, 380, 400);

        panelCrear.setVisible(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Nombre:");

        cname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnameActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Apellido:");

        csurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                csurnameActionPerformed(evt);
            }
        });

        botonGuardarCrear.setText("Guardar");
        botonGuardarCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarCrearActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Añadir nuevo Actor");

        botonVolverCrear.setText("Cancelar");
        botonVolverCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCrearLayout = new javax.swing.GroupLayout(panelCrear);
        panelCrear.setLayout(panelCrearLayout);
        panelCrearLayout.setHorizontalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(12, 12, 12)
                        .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(13, 13, 13)
                        .addComponent(csurname, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel7)
                    .addGroup(panelCrearLayout.createSequentialGroup()
                        .addComponent(botonGuardarCrear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVolverCrear)))
                .addContainerGap())
        );
        panelCrearLayout.setVerticalGroup(
            panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCrearLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(csurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(panelCrearLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonGuardarCrear)
                    .addComponent(botonVolverCrear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelCrear);
        panelCrear.setBounds(6, 6, 233, 170);

        panelBorrar.setVisible(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        botonBorrarBorrar.setText("Borrar");
        botonBorrarBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarBorrarActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("Borrar Actor");

        botonVolverBorrar.setText("Cancelar");
        botonVolverBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverBorrarActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("ID:");

        ciddel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciddelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBorrarLayout = new javax.swing.GroupLayout(panelBorrar);
        panelBorrar.setLayout(panelBorrarLayout);
        panelBorrarLayout.setHorizontalGroup(
            panelBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, panelBorrarLayout.createSequentialGroup()
                        .addComponent(botonBorrarBorrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonVolverBorrar))
                    .addGroup(panelBorrarLayout.createSequentialGroup()
                        .addGroup(panelBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ciddel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, panelBorrarLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel11)
                        .addGap(44, 44, 44)))
                .addContainerGap())
        );
        panelBorrarLayout.setVerticalGroup(
            panelBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorrarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(panelBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(ciddel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(20, 20, 20)
                .addGroup(panelBorrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonBorrarBorrar)
                    .addComponent(botonVolverBorrar))
                .addContainerGap(75, Short.MAX_VALUE))
        );

        jLayeredPane1.add(panelBorrar);
        panelBorrar.setBounds(0, 6, 233, 200);

        getContentPane().add(jLayeredPane1);
        jLayeredPane1.setBounds(134, 6, 810, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActualizarActionPerformed
        // TODO add your handling code here:
        panelCrear.setVisible(false);
        panelActualizar.setVisible(true);
        panelBorrar.setVisible(false);
    }//GEN-LAST:event_botonActualizarActionPerformed

    private void botonCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCrearActionPerformed
        // Botón Crear
        
        panelCrear.setVisible(true);
        panelActualizar.setVisible(false);
        panelBorrar.setVisible(false);
        
        
    }//GEN-LAST:event_botonCrearActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        // Botón Borrar
        panelCrear.setVisible(false);
        panelActualizar.setVisible(false);
        panelBorrar.setVisible(true);
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void cnameactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameactActionPerformed

    private void csurnameactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csurnameactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csurnameactActionPerformed

    private void botonGuardarActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActualizarActionPerformed
        //Botón Crear en Actualizar
        int actid = Integer.parseInt(cidact.getText());
        String actname = cnameact.getText();
        String actsurname = csurnameact.getText();
        
        try {
            con = getConection();
            ps = con.prepareStatement("UPDATE actor SET first_name='" +actname+"', last_name='" +actsurname+ "' WHERE actor_id='" +actid+"'");

            int res = ps.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Actor actualizado");
            } else {
                JOptionPane.showMessageDialog(null, "Error al Actualizar Actor");
            }
            //TablaDatos.setModel(modelo);

            limpiarCajas();
            actutabla();
            con.close();

        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }
        
    }//GEN-LAST:event_botonGuardarActualizarActionPerformed

    private void botonVolverActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActualizarActionPerformed
        // Botón Volver
        limpiarCajas();
        actutabla();
        panelCrear.setVisible(false);
        panelActualizar.setVisible(false);
        panelBorrar.setVisible(false);
    }//GEN-LAST:event_botonVolverActualizarActionPerformed

    private void cnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnameActionPerformed

    private void csurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_csurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_csurnameActionPerformed

    private void botonGuardarCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarCrearActionPerformed

        // Botón Guardar en Crear

        try {
            con = getConection();
            ps = con.prepareStatement("INSERT INTO actor (first_name, last_name) VALUES(?,?) ");
            ps.setString(1, cname.getText());
            ps.setString(2, csurname.getText());

            int res = ps.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Actor guardado");
            } else {
                JOptionPane.showMessageDialog(null, "Error al Crear Actor");
            }
            //TablaDatos.setModel(modelo);

            limpiarCajas();
            actutabla();
            con.close();

        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_botonGuardarCrearActionPerformed

    private void botonVolverCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverCrearActionPerformed
        // Botón Volver
        limpiarCajas();
        actutabla();
        panelCrear.setVisible(false);
        panelActualizar.setVisible(false);
        panelBorrar.setVisible(false);
    }//GEN-LAST:event_botonVolverCrearActionPerformed

    private void cidactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidactActionPerformed

    private void botonBorrarBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarBorrarActionPerformed
        //Botón Borrar en Borrar
        
        int actid = Integer.parseInt(ciddel.getText());
        
        try {
            con = getConection();
            ps = con.prepareStatement("DELETE FROM actor WHERE actor_id='" +actid+"'");

            int res = ps.executeUpdate();

            if (res > 0) {
                JOptionPane.showMessageDialog(null, "Actor borrado");
            } else {
                JOptionPane.showMessageDialog(null, "Error al Borrar Actor");
            }
            //TablaDatos.setModel(modelo);

            limpiarCajas();
            actutabla();
            con.close();

        } catch (HeadlessException | SQLException e) {
            System.err.println(e);
        }
    }//GEN-LAST:event_botonBorrarBorrarActionPerformed

    private void botonVolverBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverBorrarActionPerformed
        // Botón Volver
        limpiarCajas();
        actutabla();
        panelCrear.setVisible(false);
        panelActualizar.setVisible(false);
        panelBorrar.setVisible(false);
    }//GEN-LAST:event_botonVolverBorrarActionPerformed

    private void ciddelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciddelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciddelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CRUD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CRUD().setVisible(true);
            }
            
        });
    }
    
        private void listar() {

        String sql = "SELECT * FROM actor";
        try {
            con = getConection();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            Object[] actor = new Object[3];
            modelo = (DefaultTableModel) TablaDatos.getModel();

            while (rs.next()) {
                actor[0] = rs.getInt("actor_id");
                actor[1] = rs.getString("first_name");
                actor[2] = rs.getString("last_name");
                modelo.addRow(actor);
            }
            TablaDatos.setModel(modelo);
        } catch (Exception e) {
        }
    }
        
        public void actutabla() {
        ((DefaultTableModel) TablaDatos.getModel()).setNumRows(0);
        listar();
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu;
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton botonActualizar;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBorrarBorrar;
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonGuardarActualizar;
    private javax.swing.JButton botonGuardarCrear;
    private javax.swing.JButton botonVolverActualizar;
    private javax.swing.JButton botonVolverBorrar;
    private javax.swing.JButton botonVolverCrear;
    private javax.swing.JTextField cidact;
    private javax.swing.JTextField ciddel;
    private javax.swing.JTextField cname;
    private javax.swing.JTextField cnameact;
    private javax.swing.JTextField csurname;
    private javax.swing.JTextField csurnameact;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelActualizar;
    private javax.swing.JPanel panelBorrar;
    private javax.swing.JPanel panelCrear;
    // End of variables declaration//GEN-END:variables
}
